name: Simple Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle (without wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build shadowJar

      - name: List all files in build directory
        run: find build -name "*.jar" -type f

      - name: Upload all JARs
        uses: actions/upload-artifact@v4
        with:
          name: YoTPA-build
          path: |
            build/**/*.jar
          if-no-files-found: warn