name: Build YoTPA Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build reobfJar

      - name: List build output
        run: |
          echo "Contents of build/libs/:"
          ls -la build/libs/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: YoTPA-${{ github.sha }}
          path: |
            build/libs/YoTPA-*.jar
            build/libs/yotpa-*.jar
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/YoTPA-*.jar
            build/libs/yotpa-*.jar
          body: |
            ## YoTPA Plugin Release
            
            New release of YoTPA plugin for Paper 1.21.5+
            
            **Download:** Grab the JAR file below and place it in your server's `plugins` folder.
            
            **Requirements:**
            - Paper 1.21.5+
            - Java 21
            
            **Commands:**
            - `/tpa <player>` - Request to teleport to another player
            - `/tpahere <player>` - Request another player to teleport to you
            - `/tpaccept` - Accept a teleport request
            - `/tpadeny` - Deny a teleport request
            - `/tpareload` - Reload the plugin configuration
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}