name: Build YoTPA Plugin & Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List build output
        run: |
          echo "Contents of build/libs/:"
          ls -la build/libs/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: YoTPA-${{ github.sha }}
          path: |
            build/libs/YoTPA-*.jar
          if-no-files-found: error

      - name: Create Release
        if: ${{startsWith(github.ref, 'refs/tags')}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ github.ref_name }}
        uses: elgohr/Github-Release-Action@v5
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          prerelease: false